spring:
  application:
    name: "Consumer Microservice"
  
  datasource:
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:testdb"

logging:
  level:
    org:
      hibernate:
        SQL: "DEBUG"